# Generated by Django 3.2.6 on 2022-08-27 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220827_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalappraisal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 9, 45, 58, 995733)),
        ),
        migrations.AlterField(
            model_name='jobappraisal',
            name='appraisal_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 9, 45, 58, 995733)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 9, 45, 58, 999316)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 9, 45, 58, 995733)),
        ),
        migrations.AlterField(
            model_name='staffappraisal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 9, 45, 58, 995733)),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('select account', 'select account'), ('teacher', 'teacher'), ('management', 'management'), ('accountant', 'accountant'), ('resource management', 'resource management'), ('board member', 'board member')], default='select account', max_length=200),
        ),
    ]
