# Generated by Django 3.2.6 on 2022-10-15 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220828_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalappraisal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 16, 45, 28, 273374)),
        ),
        migrations.AlterField(
            model_name='jobappraisal',
            name='appraisal_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 16, 45, 28, 273374)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 16, 45, 28, 276066)),
        ),
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.TextField(blank=True, default='enter description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 16, 45, 28, 273374)),
        ),
        migrations.AlterField(
            model_name='staffappraisal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 16, 45, 28, 273374)),
        ),
    ]
