# Generated by Django 3.2.6 on 2022-10-15 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20221015_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalappraisal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 0, 25, 18, 702993)),
        ),
        migrations.AlterField(
            model_name='jobappraisal',
            name='appraisal_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 0, 25, 18, 702993)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 0, 25, 18, 706339)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 0, 25, 18, 702993)),
        ),
        migrations.AlterField(
            model_name='staffappraisal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 0, 25, 18, 702993)),
        ),
        migrations.AlterField(
            model_name='staffappraisal',
            name='staff_rating',
            field=models.CharField(blank=True, default='100', max_length=50),
        ),
    ]
