# Generated by Django 3.2.6 on 2022-08-27 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='default.jpeg', upload_to='profile_pics')),
                ('gender', models.CharField(choices=[('Select Gender', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='Select Gender', max_length=30)),
                ('staff_bio', models.CharField(blank=True, max_length=200)),
                ('staff_id', models.CharField(blank=True, max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, default='School Name', max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('school_type', models.CharField(blank=True, max_length=200)),
                ('staff_class', models.CharField(blank=True, default='None', max_length=200)),
                ('staff_subject', models.CharField(blank=True, max_length=200)),
                ('staff_no_of_subjects', models.IntegerField()),
                ('bank', models.CharField(default='State Your Bank', max_length=30)),
                ('account_no', models.CharField(default='Enter Account Number', max_length=30)),
                ('account_name', models.CharField(default='Enter Account Name', max_length=30)),
                ('phone_no', models.CharField(default=0, max_length=30)),
                ('address', models.TextField(default='my address', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
