# Generated by Django 3.2.6 on 2022-08-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafff', '0002_auto_20220828_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, default='Your headline', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default_profile_pic.jpeg', upload_to='media/profile_pics'),
        ),
    ]
