# Generated by Django 3.2.6 on 2022-10-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafff', '0003_auto_20220828_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default_profile_pic.jpeg', upload_to='profile_pics'),
        ),
    ]
