# Generated by Django 3.2.6 on 2022-10-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafff', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timeline',
            field=models.ImageField(blank=True, default='default_profile_pic.jpeg', upload_to='timeline_pics/'),
        ),
    ]
