# Generated by Django 3.2.6 on 2022-10-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafff', '0006_auto_20221015_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timeline',
        ),
        migrations.AddField(
            model_name='profile',
            name='timeline_picture',
            field=models.ImageField(blank=True, default='img-1-1000x600.jpg', upload_to='timeline_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default_profile_pic.jpeg', upload_to='profile_pics'),
        ),
    ]
