# Generated by Django 3.2.6 on 2022-10-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafff', '0007_auto_20221015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, default='+234-08000000', max_length=30),
        ),
    ]
